# Generated by Django 6.0.2 on 2026-02-22 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='authors/profiles/')),
            ],
        ),
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
                ('cat_slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=200)),
                ('publisher_image', models.ImageField(blank=True, help_text='Publisher ka logo', null=True, upload_to='publishers/logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products/main/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='products/covers/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('language', models.CharField(default='Hindi', max_length=50)),
                ('pages', models.PositiveIntegerField(help_text='Total number of pages')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN Number')),
                ('binding_type', models.CharField(help_text='e.g., Spiral, Paperback, Hardcover', max_length=50)),
                ('width', models.CharField(blank=True, help_text='e.g., 13 MM', max_length=50)),
                ('height', models.CharField(blank=True, help_text='e.g., 19 MM', max_length=50)),
                ('weight', models.CharField(blank=True, help_text='e.g., 117 GRAM', max_length=50)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('quality_check', models.CharField(blank=True, help_text='e.g., 32', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft (Hidden)'), ('published', 'Published (Visible)'), ('out_of_stock', 'Out of Stock')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore.author')),
                ('book_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore.booktype')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='bookstore.category')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore.publisher')),
            ],
        ),
    ]
