# Generated by Django 6.0.2 on 2026-02-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
