# Generated by Django 6.0.2 on 2026-02-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_author_author_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktype',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='publisher_slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
