# Generated by Django 6.0.2 on 2026-02-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_booktype_slug_brand_brand_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(help_text='Main display image', upload_to='products/main/'),
        ),
    ]
