# Generated by Django 6.0.2 on 2026-02-25 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_subject_product_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/main/'),
        ),
        migrations.CreateModel(
            name='ProductCoverImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload front, back, or inside cover images', upload_to='products/extra_covers/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_covers', to='bookstore.product')),
            ],
        ),
    ]
