# Generated by Django 6.0.2 on 2026-02-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0010_alter_product_image_productcoverimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCoverImage',
        ),
    ]
