# Generated by Django 6.0.2 on 2026-03-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0014_alter_coupon_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='code',
        ),
        migrations.AddField(
            model_name='coupon',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
            preserve_default=False,
        ),
    ]
