# Generated by Django 6.0.2 on 2026-03-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0015_remove_coupon_code_coupon_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='price',
        ),
        migrations.AddField(
            model_name='coupon',
            name='code',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
