# Generated by Django 6.0.2 on 2026-03-31 07:27

import django.utils.timezone
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0016_remove_coupon_price_coupon_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='amount',
            new_name='discount_amount',
        ),
        migrations.AddField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
