# Generated by Django 6.0.2 on 2026-04-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0024_coupon_discount_percent_coupon_max_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank if using percentage discount', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank if using flat discount', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount limit', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum order amount required', max_digits=10, null=True),
        ),
    ]
