# Generated by Django 6.0.2 on 2026-04-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0026_order_cancelled_order_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_buy_now',
            field=models.BooleanField(default=False),
        ),
    ]
