# Generated by Django 6.0.2 on 2026-04-06 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0028_reviewrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='subject',
        ),
    ]
