# Generated by Django 6.0.2 on 2026-04-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0029_remove_reviewrating_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isbn',
            field=models.CharField(blank=True, default='NA', max_length=20, unique=True, verbose_name='ISBN Number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quality_check',
            field=models.CharField(blank=True, default='32', help_text='e.g., 32', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft (Hidden)'), ('published', 'Published (Visible)'), ('out_of_stock', 'Out of Stock')], default='published', max_length=20),
        ),
    ]
